spring:
 application:
  name: notificationservice
 cloud:
  gcp:
   project-id: <GCP-PROJECT-ID>
   credentials:
    location: file: <PUB/SUB-SUBSCRIBER-ROLE-SERVICE-ACCOUNT-KEY-JSON-PATH>

server:
 port: 8083